# Generated by Django 3.2.4 on 2021-06-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grociapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_desc', models.CharField(max_length=50)),
                ('price', models.IntegerField(default='')),
                ('image', models.ImageField(default='', upload_to='static/images')),
            ],
        ),
        migrations.DeleteModel(
            name='items',
        ),
    ]
