# Generated by Django 3.2.4 on 2021-06-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grociapp', '0002_auto_20210621_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='biscuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biscuit_name', models.CharField(max_length=50)),
                ('biscuit_desc', models.CharField(max_length=50)),
                ('price', models.IntegerField(default='0')),
                ('image', models.ImageField(default='0', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='disinfecent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disinfecent_name', models.CharField(max_length=50)),
                ('disinfecent_desc', models.CharField(max_length=50)),
                ('price', models.IntegerField(default='0')),
                ('image', models.ImageField(default='0', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=50)),
                ('drink_desc', models.CharField(max_length=50)),
                ('price', models.IntegerField(default='0')),
                ('image', models.ImageField(default='0', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=50)),
                ('fruit_desc', models.CharField(max_length=50)),
                ('price', models.IntegerField(default='0')),
                ('image', models.ImageField(default='0', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='milk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_name', models.CharField(max_length=50)),
                ('milk_desc', models.CharField(max_length=50)),
                ('price', models.IntegerField(default='0')),
                ('image', models.ImageField(default='0', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='noodle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noodle_name', models.CharField(max_length=50)),
                ('noodle_desc', models.CharField(max_length=50)),
                ('price', models.IntegerField(default='0')),
                ('image', models.ImageField(default='0', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='pulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse_name', models.CharField(max_length=50)),
                ('pulse_desc', models.CharField(max_length=50)),
                ('price', models.IntegerField(default='0')),
                ('image', models.ImageField(default='0', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='staple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staple_name', models.CharField(max_length=50)),
                ('staple_desc', models.CharField(max_length=50)),
                ('price', models.IntegerField(default='0')),
                ('image', models.ImageField(default='0', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='utensil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utensil_name', models.CharField(max_length=50)),
                ('utensil_desc', models.CharField(max_length=50)),
                ('price', models.IntegerField(default='0')),
                ('image', models.ImageField(default='0', upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='0', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default='0'),
        ),
    ]
